"""add composite indexes on messages

Revision ID: f12eb3c45d16
Revises: 90de48a2bfd3
Create Date: 2026-04-10 02:00:41.890952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f12eb3c45d16'
down_revision: Union[str, Sequence[str], None] = '90de48a2bfd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('lobby_time_idx', 'messages', ['created_at'], unique=False, postgresql_where=sa.text('room_id IS NULL'))
    op.create_index('room_time_idx', 'messages', ['room_id', 'created_at'], unique=False)
    op.create_index('user_time_idx', 'messages', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_time_idx', table_name='messages')
    op.drop_index('room_time_idx', table_name='messages')
    op.drop_index('lobby_time_idx', table_name='messages', postgresql_where=sa.text('room_id IS NULL'))
    # ### end Alembic commands ###
